---
title: "ARCHS4 - Data preprocess"
output: html_document
---

```{r load_config}
library(here)
source(here("config.R"))
```

```{r load_functions}
source(here("R/utilsNew.R"))
```

```{r load_libraries}
library(hdf5r)
library(biomaRt)
library(dplyr)
```

```{r paths}
output_dir <- config$ARCHS4$DATASET_FOLDER
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
```

```{r read_input_data}
file_path <- config$ARCHS4$DATASET_FILE

h5        <- H5File$new(file_path, mode = "r")
dset      <- h5[["/data/expression"]]
gene_symbols <- h5[["/meta/genes/symbol"]]$read()
gene_ids     <- h5[["/meta/genes/ensembl_gene"]]$read()
sample_names <- h5[["/meta/samples/geo_accession"]]$read()
n_genes      <- length(gene_symbols)
n_samples    <- length(sample_names)
```

Get gene lengths for this Ensembl version

```{r get_gene_lengths}
# TODO: check, I'm not entirely sure if this is the best way to get gene
# lengths (using EDASeq, below, was giving an error)
output_file <- file.path(output_dir, "gene_lengths.rds")

ensembl_ver <- config$ARCHS4$DATASET_ENSEMBL_VERSION
ensembl <- useEnsembl(biomart="ensembl", version=ensembl_ver)
mart <- biomaRt::useDataset("hsapiens_gene_ensembl", ensembl)
gene_info <- biomaRt::getBM(
  filters = "hgnc_symbol",
  attributes = c("ensembl_gene_id", "hgnc_symbol", "transcript_length"),
  values = gene_symbols, 
  mart = mart
)

gene_lengths <- gene_info %>%
  group_by(hgnc_symbol, ensembl_gene_id) %>%
  summarize(gene_length_bp = max(transcript_length, na.rm = TRUE)) %>%
  pull(gene_length_bp, name = hgnc_symbol)

#saveRDS(gene_lengths, file = output_file)

# Using EDASeq:
#
#if (!file.exists(output_file)) {
#  gene_lengths <- EDASeq::getGeneLengthAndGCContent(gene_ids, "hsa")
#  saveRDS(gene_lengths, file = output_file)
#} else {
#  gene_lengths <- readRDS(output_file)
#  cat("File already exists. Skipping download.\n")
#}
```

Since we don't get gene lengths (needed for TPM normalization) for every input gene, we'll use only those for which length info is available:

```{r adjust_gene_symbols}
# keep in data only genes for which we have lengths
# here gene symbols are duplicated (we'll use that later)
gene_symbols_idx <- which( gene_symbols %in% names(gene_lengths) )
gene_symbols_thin <- gene_symbols[gene_symbols_idx]

# get unique gene symbols
# since we are gonna use rowsum to aggregate same gene symbols, I use it here
# to get a list of unique and fixed gene symbols
summed <- rowsum(t(dset[1:10, gene_symbols_idx]), group = gene_symbols_thin)
gene_symbols_thin_unique <- rownames(summed)
stopifnot(length(gene_symbols_thin_unique) == length(unique(gene_symbols_thin)))
gene_lengths <- gene_lengths[gene_symbols_thin_unique]
n_genes_thin <- length(gene_symbols_thin_unique)
rm(summed)

saveRDS(
  list(
#    gene_symbols_idx=gene_symbols_idx,
    gene_symbols_thin=gene_symbols_thin_unique,
    gene_lengths=gene_lengths,
    n_genes_thin=n_genes_thin,
    n_samples=n_samples
  ),
  file.path(output_dir, "metadata.rds")
)
```

Create or open FBM matrix

```{r create_fbm}
fbm_file  <- file.path(output_dir, "fbm")

fbm_file_path <- paste0(fbm_file, ".bk")
if (file.exists(fbm_file_path)) {
  file.remove(fbm_file_path)
}

fbm_obj <- FBM(
  nrow        = n_genes_thin,
  ncol        = n_samples,
  backingfile = fbm_file,
  create_bk   = TRUE,
)
```

Populate it with data

```{r populate_fbm}
# FIXME: here I override the CHUNK_SIZE value since there is an error in reading
# ARCHS4 at some block
block_size <- 100 # config$GENERAL$CHUNK_SIZE
n_blocks   <- ceiling(n_samples / block_size)

pb <- txtProgressBar(min = 0, max = n_blocks, style = 3)

for (i in 1:n_blocks) {
  setTxtProgressBar(pb, i)

  start_row <- (i-1) * block_size + 1
  end_row <- min(i * block_size, n_samples)

  raw_block <- NULL
  tryCatch(
    expr = {
      raw_block <- dset[start_row:end_row, ]
    },
    error = function(e) {
      message(paste("Error with block: ", i))
    }
  )
  if (is.null(raw_block)) {
    # FIXME: I add a dummy block here with near-to-zero values; not sure if
    # this is the best approach here; for some reason, there is a block that
    # cannot be read in ARCHS4, so I "skip" it here
    raw_block <- matrix(1e-10, (end_row - start_row + 1), n_genes)
  }

  # subset genes to those with gene length only
  raw_block <- raw_block[, gene_symbols_idx]

  # aggregate duplicated gene symbols
  raw_block_t <- t(raw_block)
  raw_block_summed <- rowsum(raw_block_t, group = gene_symbols_thin)
  raw_block <- t(raw_block_summed)
  rownames(raw_block) <- NULL

  # tpm normalize
  raw_block <- t(tpm_norm(raw_block, gene_lengths))

  fbm_obj[, start_row:end_row] <- as.matrix(raw_block)
}
```

Once done, close h5 file

```{r close_h5}
h5$close_all()
```

```{r clean_fbm}
N_CORES <- config$GENERAL$N_CORES
if (N_CORES > 1) {
  # if we are parallelizing, then disable BLAS parallelization
  options(bigstatsr.check.parallel.blas = FALSE)
  blas_nproc <- getOption("default.nproc.blas")
  options(default.nproc.blas = NULL)
}

# run cleanFBM (log, NAs handling, etc)
cleanFBM(fbm_obj, ncores=N_CORES)

if (N_CORES > 1) {
  options(bigstatsr.check.parallel.blas = TRUE)
  options(default.nproc.blas = blas_nproc)
}
```

