---
title: "ARCHS4 - Data filtering"
output: html_document
---

```{r load_config}
library(here)
source(here("config.R"))
```

```{r load_functions}
source(here("R/utilsNew.R"))
```

```{r load_libraries}

```

```{r paths}
output_dir <- config$ARCHS4$DATASET_FOLDER
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
```

```{r}
meta <- readRDS(file.path(output_dir, "metadata.rds"))
gene_symbols_idx <- meta$gene_symbols_idx
gene_symbols_thin <- meta$gene_symbols_thin
gene_lengths <- meta$gene_lengths
n_genes_thin <- meta$n_genes_thin
n_samples <- meta$n_samples
```


```{r}
fbm_file  <- file.path(output_dir, "fbm")

fbm_obj <- FBM(
  nrow        = n_genes_thin,
  ncol        = n_samples,
  backingfile = fbm_file,
  create_bk   = FALSE,
)
```


Compute gene stats

```{r get_fbm_stats_and_plot}
#output_file <- file.path(output_dir, "row_stats.rds")

options(bigstatsr.check.parallel.blas = FALSE)
blas_nproc <- getOption("default.nproc.blas")
options(default.nproc.blas = NULL)

#if (!file.exists(output_file)) {
  rowStats=computeRowStatsFBM(fbm_obj, ncores=config$GENERAL$N_CORES)
#  saveRDS(rowStats, file = output_file)

  png(filename=file.path(output_dir, "gene_means_and_vars.png"))
  plot(rowStats$row_means, rowStats$row_variances, log="y")
  dev.off()
#} else {
#  rowStats <- readRDS(output_file)
#}
options(bigstatsr.check.parallel.blas = TRUE)
options(default.nproc.blas = blas_nproc)
```

Filter the data. Doing aggressive filtering to reduce the number of genes.

```{r filter_fbm}
output_file <- paste0(fbm_file, "_filtered")
#kept_rows_output_file <- file.path(output_nb_path, "kept_rows.rds")

#if (!file.exists(output_file)) {
filterResult=filterFBM(
	fbm_obj,
	rowStats,
	mean_cutoff = config$ARCHS4$GENES_MEAN_CUTOFF,
	var_cutoff = config$ARCHS4$GENES_VAR_CUTOFF,
	backingfile = output_file
)

#  saveRDS(filterResult$kept_rows, kept_rows_output_file)


  
#} else {
#  filterResult <- list()

#	filterResult$fbm_filtered <- FBM(
#		nrow        = n_genes_thin,
#		ncol        = n_samples,
#		backingfile = fbm_file,
#		create_bk   = !fbm_file_exists,
#	)

#  filterResult$kept_rows <- readRDS(kept_rows_output_file)
#}

fbm_obj_filtered=filterResult$fbm_filtered
```

```{r}
message(paste("New filtered dataset dims: ", nrow(fbm_obj_filtered), " x ", ncol(fbm_obj_filtered)))
```

```{r update_gene_symbols}
# update
gene_symbols_thin=gene_symbols_thin[filterResult$kept_rows]
n_genes_thin <- length(gene_symbols_thin)

# save
saveRDS(
  list(
    gene_symbols_idx=gene_symbols_idx,
    gene_symbols_thin=gene_symbols_thin,
    gene_lengths=gene_lengths,
    n_genes_thin=n_genes_thin,
    n_samples=n_samples
  ),
  file.path(output_dir, "metadata.rds")
)
```

```{r}
message(paste("Number of genes kept: ", length(gene_symbols_thin)))
```

```{r}
rowStats$row_means=rowStats$row_means[filterResult$kept_rows]
rowStats$row_variances=rowStats$row_variances[filterResult$kept_rows]
```


```{r zscore}
# TODO: add a way to check if this needs to be done
zscoreFBM(fbm_obj_filtered, rowStats = rowStats, chunk_size=config$GENERAL$CHUNK_SIZE)
```

