---
title: "ARCHS4 - Simple PLIER Decomposition"
output: html_document
---

```{r load_config}
library(here)
source(here("config.R"))
```

```{r load_functions}
source(here("R/solvers.R"))
source(here("R/utilsNew.R"))
```

```{r load_libraries}

```

```{r paths}
output_dir <- config$ARCHS4$DATASET_FOLDER
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
```

```{r}
meta <- readRDS(file.path(output_dir, "metadata_filtered.rds"))
gene_symbols_idx <- meta$gene_symbols_idx
gene_symbols_thin <- meta$gene_symbols_thin
gene_lengths <- meta$gene_lengths
n_genes_thin <- meta$n_genes_thin
n_samples <- meta$n_samples
```


```{r}
fbm_file  <- file.path(output_dir, "fbm")
output_file <- paste0(fbm_file, "_filtered")

fbm_obj_filtered <- FBM(
  nrow        = n_genes_thin,
  ncol        = n_samples,
  backingfile = output_file ,
  create_bk   = FALSE,
)
```

Precompute the SVD

```{r randomSVD}
set.seed(config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_SEED)

if (config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_N_CORES > 1) {
  # if we are parallelizing big_randomSVD, then disable BLAS parallelization
  options(bigstatsr.check.parallel.blas = FALSE)
  blas_nproc <- getOption("default.nproc.blas")
  options(default.nproc.blas = NULL)
}

fbm_obj.svd=big_randomSVD(
  fbm_obj_filtered,
  k = config$ARCHS4$PLIER_PARAMS$K,
  ncores = config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_N_CORES
)

if (config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_N_CORES > 1) {
  # restore previous state
  options(bigstatsr.check.parallel.blas = TRUE)
  options(default.nproc.blas = blas_nproc)
}
```

Run simpleDecomp as the base model

```{r simpleDecomp}
decomp_file <- file.path(output_dir, "simpleDecompResult.rds")

#if (!file.exists(decomp_file)) {
  fbm_obj.sdres <- simpleDecomp(
    fbm_obj_filtered,
    k = config$ARCHS4$PLIER_PARAMS$K,
    svdres = fbm_obj.svd,
    ncores = config$ARCHS4$PLIER_PARAMS$N_CORES
  )

  saveRDS(fbm_obj.sdres, file = decomp_file)
#} else {
#  fbm_obj.sdres <- readRDS(decomp_file)
#}
```

