---
title: "ARCHS4 - Simple PLIER Decomposition"
output: html_document
---

```{r load_config}
library(here)
source(here("config.R"))
```

```{r load_functions}
#source(here("R/solvers.R"))
source(here("R/utilsNew.R"))
```

```{r load_libraries}

```

```{r paths}
output_dir <- config$ARCHS4$DATASET_FOLDER
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
```

```{r load_meta}
meta <- readRDS(file.path(output_dir, "metadata_filtered.rds"))
#gene_symbols_idx <- meta$gene_symbols_idx
#gene_symbols_thin <- meta$gene_symbols_thin
#gene_lengths <- meta$gene_lengths
n_genes_thin <- meta$n_genes_thin
n_samples <- meta$n_samples
```


```{r open_fbm_file}
fbm_file  <- file.path(output_dir, "fbm")
output_file <- paste0(fbm_file, "_filtered")

fbm_obj_filtered <- FBM(
  nrow        = n_genes_thin,
  ncol        = n_samples,
  backingfile = output_file ,
  create_bk   = FALSE,
)
```

K for SVD

```{r k, echo=TRUE}
SVD_K <- min(n_genes_thin, n_samples) - 1
message(SVD_K)
```

Precompute the SVD

```{r randomSVD}
set.seed(config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_SEED)
output_file <- file.path(output_dir, "svd.rds")

N_CORES <- config$ARCHS4$PLIER_PARAMS$RANDOM_SVD_N_CORES
if (N_CORES > 1) {
  # if we are parallelizing, then disable BLAS parallelization
  options(bigstatsr.check.parallel.blas = FALSE)
  blas_nproc <- getOption("default.nproc.blas")
  options(default.nproc.blas = NULL)
}

fbm_obj.svd=big_randomSVD(
  fbm_obj_filtered,
  k = SVD_K,
  ncores = N_CORES
)

if (N_CORES > 1) {
  # restore previous state
  options(bigstatsr.check.parallel.blas = TRUE)
  options(default.nproc.blas = blas_nproc)
}

saveRDS(fbm_obj.svd, file = output_file)
```

Infer K from SVD using elbow method

```{r infer_k, echo=TRUE}
PLIER_K <- num.pc(fbm_obj.svd) * 2

message(paste0("K inferred for PLIER: ", PLIER_K))
```

